name: flutter_application_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  audio_io: ^0.3.0
  flutter_audio_capture: ^1.1.11
  fftea: ^1.5.0+1
  permission_handler: ^11.3.1
  flutter_audio_output: ^0.0.4
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
